/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use B8CF2B29-69EA-4BF3-869A-88E18CBB90E7 instead of MulleHoedown if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark MulleHoedown no-header`
//    rename:              `mulle-sde dependency|library set MulleHoedown include whatever.h`
//    reorder:             `mulle-sde dependency move MulleHoedown <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleHoedown [no-]import`
//    toggle public:       `mulle-sde dependency mark MulleHoedown [no-]public`
//    toggle optional:     `mulle-sde dependency mark MulleHoedown [no-]require`
//    remove for platform: `mulle-sde dependency mark MulleHoedown no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleHoedown/MulleHoedown.h>   // MulleHoedown

#ifdef __has_include
# if __has_include( "_mulle-testproto-include.h")
#  include "_mulle-testproto-include.h"
# endif
#endif

